In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pylab as plt
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [2]:
df = pd.read_csv('D600 Task 3 Dataset 1 Housing Information.csv')

In [3]:
df.head()

,ID,Price,SquareFootage,NumBathrooms,NumBedrooms,BackyardSpace,CrimeRate,SchoolRating,AgeOfHome,DistanceToCityCenter,...,RenovationQuality,LocalAmenities,TransportAccess,Fireplace,HouseColor,Garage,Floors,Windows,PreviousSalePrice,IsLuxury
0,4922,255614.8992,566.62,1.000000,4,779.42,20.56,5.62,39.46,10.08,...,4.93,4.44,4.55,Yes,Blue,No,1,13,181861.54230,0
1,5009,155586.0947,1472.34,1.000000,2,656.13,15.62,5.63,40.51,7.89,...,4.08,5.56,6.83,No,Green,No,1,17,50042.59757,0
2,4450,131050.8324,550.00,1.779354,3,754.57,12.47,9.20,48.38,23.74,...,4.26,8.07,8.48,Yes,Green,Yes,2,34,48400.34440,0
3,1070,151361.7125,941.81,2.035254,2,439.59,22.22,7.08,94.67,5.22,...,4.45,5.00,6.27,Yes,Red,No,1,14,84594.12145,0
4,400,113167.6128,550.00,1.064644,3,353.03,8.28,5.93,16.80,43.13,...,3.36,5.46,6.99,No,White,Yes,1,21,22934.59654,0

In [4]:
features = ["SquareFootage", "NumBathrooms", "BackyardSpace", "CrimeRate", 
                  "SchoolRating", "AgeOfHome", "DistanceToCityCenter", "EmploymentRate", "PropertyTaxRate",
                  "RenovationQuality", "LocalAmenities", "PreviousSalePrice"]
output = ['Price']
df[features].head()

,SquareFootage,NumBathrooms,BackyardSpace,CrimeRate,SchoolRating,AgeOfHome,DistanceToCityCenter,EmploymentRate,PropertyTaxRate,RenovationQuality,LocalAmenities,PreviousSalePrice
0,566.62,1.000000,779.42,20.56,5.62,39.46,10.08,97.29,1.84,4.93,4.44,181861.54230
1,1472.34,1.000000,656.13,15.62,5.63,40.51,7.89,93.22,0.95,4.08,5.56,50042.59757
2,550.00,1.779354,754.57,12.47,9.20,48.38,23.74,96.60,1.87,4.26,8.07,48400.34440
3,941.81,2.035254,439.59,22.22,7.08,94.67,5.22,91.45,1.45,4.45,5.00,84594.12145
4,550.00,1.064644,353.03,8.28,5.93,16.80,43.13,86.50,1.26,3.36,5.46,22934.59654

In [5]:
df[features].dtypes

SquareFootage           float64
NumBathrooms            float64
BackyardSpace           float64
CrimeRate               float64
SchoolRating            float64
AgeOfHome               float64
DistanceToCityCenter    float64
EmploymentRate          float64
PropertyTaxRate         float64
RenovationQuality       float64
LocalAmenities          float64
PreviousSalePrice       float64
dtype: object

In [6]:
df[features].describe()

,SquareFootage,NumBathrooms,BackyardSpace,CrimeRate,SchoolRating,AgeOfHome,DistanceToCityCenter,EmploymentRate,PropertyTaxRate,RenovationQuality,LocalAmenities,PreviousSalePrice
count,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7.000000e+03
mean,1048.947459,2.131397,511.507029,31.226194,6.942923,46.797046,17.475337,93.711349,1.500437,5.003357,5.934579,2.845094e+05
std,426.010482,0.952561,279.926549,18.025327,1.888148,31.779701,12.024985,4.505359,0.498591,1.970428,2.657930,1.857340e+05
min,550.000000,1.000000,0.390000,0.030000,0.220000,0.010000,0.000000,72.050000,0.010000,0.010000,0.000000,-8.356902e+03
25%,660.815000,1.290539,300.995000,17.390000,5.650000,20.755000,7.827500,90.620000,1.160000,3.660000,4.000000,1.420140e+05
50%,996.320000,1.997774,495.965000,30.385000,7.010000,42.620000,15.625000,94.010000,1.490000,5.020000,6.040000,2.621831e+05
75%,1342.292500,2.763997,704.012500,43.670000,8.360000,67.232500,25.222500,97.410000,1.840000,6.350000,8.050000,3.961212e+05
max,2874.700000,5.807239,1631.360000,99.730000,10.000000,178.680000,65.200000,99.900000,3.360000,10.000000,10.000000,1.296607e+06

In [7]:
df[features].to_csv('Cleaned D600 Task 3 Dataset 1 Housing Information.csv', index=True)

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
features_std = scaler.fit_transform(df[features])
features_std_df = pd.DataFrame(features_std, columns=features, index=df.index)

print(features_std_df.head())

   SquareFootage  NumBathrooms  BackyardSpace  CrimeRate  SchoolRating  \
0      -1.132277     -1.187828       0.957151  -0.591776     -0.700696
1       0.993926     -1.187828       0.516683  -0.865854     -0.695399
2      -1.171293     -0.369602       0.868372  -1.040621      1.195478
3      -0.251508     -0.100938      -0.256932  -0.499677      0.072604
4      -1.171293     -1.119960      -0.566178  -1.273088     -0.536502

   AgeOfHome  DistanceToCityCenter  EmploymentRate  PropertyTaxRate  \
0  -0.230889             -0.615042        0.794367         0.681094
1  -0.197846             -0.797175       -0.109066        -1.104064
2   0.049814              0.521008        0.641205         0.741268
3   1.506508             -1.019229       -0.501960        -0.101167
4  -0.943973              2.133599       -1.600730        -0.482268

   RenovationQuality  LocalAmenities  PreviousSalePrice
0          -0.037232       -0.562349          -0.552700
1          -0.468641       -0.140939          -1.262469
2          -0.377284        0.803473          -1.271312
3          -0.280851       -0.351644          -1.076429
4          -0.834070       -0.178565          -1.408430